### ISSUE TITLE
Distinguish between guest and logged-in user permissions

### ISSUE THREAD

**Issue by Chiaraliz** [simonli66666/CITS5505-Project#1]
Feature: Distinguish between guest and logged-in user permissions

Proposed Implementation: First check the user's login status, if the user is not logged in, he/she can only search recipes, browse recipes and click to view recipe details, and if he/she wants to experience other functions (e.g. posting recipes), the login box will pop up.

**Comment by Chiaraliz** [comment]
Display different pages for users who are logged in and not. For users logged in, they can access login.html, Badges.html, postDetails.html and user.html. For users who are not logged in, they can only access index.html and postDetails_notlogin.html

**Comment by simonli66666** [comment]
For non-logged-in users who wish to access postDetails_notlogin.html, how can they access these uploaded recipes? Is it through the recipe menu on the index.html homepage?

**Comment by Chiaraliz** [comment]
> For non-logged-in users who wish to access postDetails_notlogin.html, how can they access these uploaded recipes? Is it through the recipe menu on the index.html homepage?

Yes, I may need to add a back button to the postDetails_notlogin.html and postsDetails.html pages
